#ifndef triangle_info
#define triangle_info

#include "triangle.hpp"

/*****************************************************************************
 *************** THIS IS AN AUTOGENERATED FILE. DO NOT MODIFY! ***************
 *****************************************************************************/

typedef void (Triangle::*TrMemberFuncPtr)();
typedef unordered_map<string, pair<long_d*, int>> TrElemPtrMap;
typedef vector<TrMemberFuncPtr>                   TrFuncPtrVec;

class TriangleInfo
{
private:
    Triangle* tr;

public:
    TriangleInfo(Triangle * const _tr) : tr(_tr)
    {

    }

    const TrFuncPtrVec get_tr_func_ptr_vec()
    {
        return {
            &Triangle::dummy_update_sides,
            &Triangle::init_sinA_sinB_sinC,
            &Triangle::init_sin2A_sin2B_sin2C,
            &Triangle::init_sin3A_sin3B_sin3C,
            &Triangle::init_cosA_cosB_cosC,
            &Triangle::init_cos2A_cos2B_cos2C,
            &Triangle::init_cos3A_cos3B_cos3C,
            &Triangle::init_tanA_tanB_tanC,
            &Triangle::init_cotA_cotB_cotC,
            &Triangle::init_sinA2_sinB2_sinC2,
            &Triangle::init_cosA2_cosB2_cosC2,
            &Triangle::init_tanA2_tanB2_tanC2,
            &Triangle::init_tanA4_tanB4_tanC4,
            &Triangle::init_cotA2_cotB2_cotC2,
            &Triangle::init_cotA4_cotB4_cotC4,
            &Triangle::init_K,
            &Triangle::init_Q,
            &Triangle::init_FT,
            &Triangle::init_OI,
            &Triangle::init_IH,
            &Triangle::init_OG,
            &Triangle::init_ha_hb_hc,
            &Triangle::init_la_lb_lc,
            &Triangle::init_ma_mb_mc,
            &Triangle::init_sa_sb_sc,
            &Triangle::init_ra_rb_rc,
            &Triangle::init_na_nb_nc,
            &Triangle::init_HA_HB_HC,
            &Triangle::init_IA_IB_IC,
            &Triangle::init_KA_KB_KC,
            &Triangle::init_GA_GB_GC,
            &Triangle::init_NA_NB_NC,
            &Triangle::init_FA_FB_FC,
            NULL
        };
    }

    const TrElemPtrMap get_tr_elem_ptr_map()
    {
        return {
            { "a", { &tr->a, 0 } },
            { "b", { &tr->b, 0 } },
            { "c", { &tr->c, 0 } },
            { "A", { &tr->A, 0 } },
            { "B", { &tr->B, 0 } },
            { "C", { &tr->C, 0 } },
            { "R", { &tr->R, 0 } },
            { "r", { &tr->r, 0 } },
            { "s", { &tr->s, 0 } },
            { "S", { &tr->S, 0 } },
            
            { "sinA", { &tr->sinA, 1 } },
            { "sinB", { &tr->sinB, 1 } },
            { "sinC", { &tr->sinC, 1 } },
            
            { "sin2A", { &tr->sin2A, 2 } },
            { "sin2B", { &tr->sin2B, 2 } },
            { "sin2C", { &tr->sin2C, 2 } },
            
            { "sin3A", { &tr->sin3A, 3 } },
            { "sin3B", { &tr->sin3B, 3 } },
            { "sin3C", { &tr->sin3C, 3 } },
            
            { "cosA", { &tr->cosA, 4 } },
            { "cosB", { &tr->cosB, 4 } },
            { "cosC", { &tr->cosC, 4 } },
            
            { "cos2A", { &tr->cos2A, 5 } },
            { "cos2B", { &tr->cos2B, 5 } },
            { "cos2C", { &tr->cos2C, 5 } },
            
            { "cos3A", { &tr->cos3A, 6 } },
            { "cos3B", { &tr->cos3B, 6 } },
            { "cos3C", { &tr->cos3C, 6 } },
            
            { "tanA", { &tr->tanA, 7 } },
            { "tanB", { &tr->tanB, 7 } },
            { "tanC", { &tr->tanC, 7 } },
            
            { "cotA", { &tr->cotA, 8 } },
            { "cotB", { &tr->cotB, 8 } },
            { "cotC", { &tr->cotC, 8 } },
            
            { "sinA2", { &tr->sinA2, 9 } },
            { "sinB2", { &tr->sinB2, 9 } },
            { "sinC2", { &tr->sinC2, 9 } },
            
            { "cosA2", { &tr->cosA2, 10 } },
            { "cosB2", { &tr->cosB2, 10 } },
            { "cosC2", { &tr->cosC2, 10 } },
            
            { "tanA2", { &tr->tanA2, 11 } },
            { "tanB2", { &tr->tanB2, 11 } },
            { "tanC2", { &tr->tanC2, 11 } },
            
            { "tanA4", { &tr->tanA4, 12 } },
            { "tanB4", { &tr->tanB4, 12 } },
            { "tanC4", { &tr->tanC4, 12 } },
            
            { "cotA2", { &tr->cotA2, 13 } },
            { "cotB2", { &tr->cotB2, 13 } },
            { "cotC2", { &tr->cotC2, 13 } },
            
            { "cotA4", { &tr->cotA4, 14 } },
            { "cotB4", { &tr->cotB4, 14 } },
            { "cotC4", { &tr->cotC4, 14 } },
            
            { "K", { &tr->K, 15 } },
            
            { "Q", { &tr->Q, 16 } },
            
            { "FT", { &tr->FT, 17 } },
            
            { "OI", { &tr->OI, 18 } },
            { "IO", { &tr->OI, 18 } },
            
            { "IH", { &tr->IH, 19 } },
            { "HI", { &tr->IH, 19 } },
            
            { "OG", { &tr->OG, 20 } },
            { "GO", { &tr->OG, 20 } },
            
            { "ha", { &tr->ha, 21 } },
            { "hb", { &tr->hb, 21 } },
            { "hc", { &tr->hc, 21 } },
            
            { "la", { &tr->la, 22 } },
            { "lb", { &tr->lb, 22 } },
            { "lc", { &tr->lc, 22 } },
            
            { "ma", { &tr->ma, 23 } },
            { "mb", { &tr->mb, 23 } },
            { "mc", { &tr->mc, 23 } },
            
            { "sa", { &tr->sa, 24 } },
            { "sb", { &tr->sb, 24 } },
            { "sc", { &tr->sc, 24 } },
            
            { "ra", { &tr->ra, 25 } },
            { "rb", { &tr->rb, 25 } },
            { "rc", { &tr->rc, 25 } },
            
            { "na", { &tr->na, 26 } },
            { "nb", { &tr->nb, 26 } },
            { "nc", { &tr->nc, 26 } },
            
            { "HA", { &tr->HA, 27 } },
            { "HB", { &tr->HB, 27 } },
            { "HC", { &tr->HC, 27 } },
            
            { "IA", { &tr->IA, 28 } },
            { "IB", { &tr->IB, 28 } },
            { "IC", { &tr->IC, 28 } },
            
            { "KA", { &tr->KA, 29 } },
            { "KB", { &tr->KB, 29 } },
            { "KC", { &tr->KC, 29 } },
            
            { "GA", { &tr->GA, 30 } },
            { "GB", { &tr->GB, 30 } },
            { "GC", { &tr->GC, 30 } },
            
            { "NA", { &tr->NA, 31 } },
            { "NB", { &tr->NB, 31 } },
            { "NC", { &tr->NC, 31 } },
            
            { "FA", { &tr->FA, 32 } },
            { "FB", { &tr->FB, 32 } },
            { "FC", { &tr->FC, 32 } },
            
            { "", { NULL, 0 } }
        };
    }
};

#endif /* triangle_info */
